// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

// package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Organization struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" ddb:"organization_id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" ddb:"name"`
	ContactName          string   `protobuf:"bytes,3,opt,name=contactName,proto3" json:"contactName,omitempty" ddb:"contact_name"`
	ContactEmail         string   `protobuf:"bytes,4,opt,name=contactEmail,proto3" json:"contactEmail,omitempty" ddb:"contact_email"`
	ContactPhone         string   `protobuf:"bytes,5,opt,name=contactPhone,proto3" json:"contactPhone,omitempty" ddb:"contact_phone"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *Organization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(m, src)
}
func (m *Organization) XXX_Size() int {
	return m.Size()
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

type GetOrgReq struct {
	OrganizationId       string   `protobuf:"bytes,1,opt,name=organizationId,proto3" json:"organizationId,omitempty" form:"organizationId" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrgReq) Reset()         { *m = GetOrgReq{} }
func (m *GetOrgReq) String() string { return proto.CompactTextString(m) }
func (*GetOrgReq) ProtoMessage()    {}
func (*GetOrgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *GetOrgReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetOrgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetOrgReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetOrgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrgReq.Merge(m, src)
}
func (m *GetOrgReq) XXX_Size() int {
	return m.Size()
}
func (m *GetOrgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrgReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrgReq proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Organization)(nil), "eagle.organization.v1.Organization")
	proto.RegisterType((*GetOrgReq)(nil), "eagle.organization.v1.GetOrgReq")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x9b, 0xec, 0x2a, 0xec, 0x58, 0xbb, 0x30, 0xb2, 0x75, 0x1b, 0x25, 0x59, 0xc6, 0x8b,
	0x15, 0x3a, 0x8b, 0x0a, 0x22, 0xf5, 0x64, 0xb1, 0x48, 0x2f, 0xb6, 0x44, 0x7a, 0xf1, 0x52, 0x26,
	0x3b, 0xd3, 0xd9, 0x81, 0x64, 0x26, 0x8d, 0xb3, 0x0b, 0x7a, 0xf4, 0x1b, 0x88, 0x17, 0x3f, 0x52,
	0x8f, 0x82, 0xf7, 0xa0, 0xab, 0x9f, 0x20, 0xe0, 0x5d, 0x32, 0xc9, 0xba, 0x93, 0xd5, 0x80, 0x07,
	0xbd, 0x65, 0xe6, 0xff, 0xfb, 0xbf, 0xff, 0xbc, 0xf7, 0x02, 0x7a, 0x24, 0x15, 0x38, 0xcd, 0x94,
	0x56, 0x70, 0xc0, 0x08, 0x8f, 0x19, 0x56, 0x19, 0x27, 0x52, 0xbc, 0x25, 0x5a, 0x28, 0x89, 0xe7,
	0xf7, 0xbd, 0x3d, 0x2e, 0xf4, 0x74, 0x16, 0xe1, 0x89, 0x4a, 0xc6, 0x5c, 0x71, 0x35, 0x36, 0x74,
	0x34, 0x3b, 0x37, 0x27, 0x73, 0x30, 0x5f, 0x55, 0x15, 0xef, 0x16, 0x57, 0x8a, 0xc7, 0x6c, 0x45,
	0xb1, 0x24, 0xd5, 0x6f, 0x6a, 0xf1, 0x76, 0x2d, 0x92, 0x54, 0x8c, 0x89, 0x94, 0x4a, 0x9b, 0x94,
	0xd7, 0x95, 0x8a, 0xde, 0xbb, 0x60, 0xf3, 0xd8, 0x4a, 0x87, 0xbb, 0xc0, 0x15, 0x74, 0xe8, 0x8c,
	0x9c, 0xbb, 0xbd, 0x83, 0x9d, 0x22, 0x0f, 0x06, 0x94, 0x46, 0xfb, 0xc8, 0x7e, 0xe0, 0x99, 0xa0,
	0x28, 0x74, 0x05, 0x85, 0x08, 0x74, 0x25, 0x49, 0xd8, 0xd0, 0x35, 0xf0, 0x56, 0x91, 0x07, 0xc0,
	0xc0, 0xe5, 0x25, 0x0a, 0x8d, 0x06, 0x1f, 0x83, 0x6b, 0x13, 0x25, 0x35, 0x99, 0xe8, 0x17, 0x25,
	0xda, 0x31, 0xe8, 0x76, 0x91, 0x07, 0xd0, 0xa0, 0xb5, 0x76, 0x56, 0x59, 0x6c, 0x14, 0x3e, 0x01,
	0x9b, 0xf5, 0xf1, 0x30, 0x21, 0x22, 0x1e, 0x76, 0x8d, 0xf5, 0x66, 0x91, 0x07, 0x37, 0x1a, 0x56,
	0x56, 0xaa, 0x28, 0x6c, 0xc0, 0x96, 0xf9, 0x64, 0xaa, 0x24, 0x1b, 0x5e, 0x69, 0x31, 0xa7, 0xa5,
	0xba, 0x32, 0x1b, 0x18, 0x45, 0xa0, 0xf7, 0x9c, 0xe9, 0xe3, 0x8c, 0x87, 0xec, 0x02, 0x9e, 0x82,
	0x2d, 0xbb, 0xf9, 0xa3, 0xe5, 0x6c, 0xf6, 0x8a, 0x3c, 0xd8, 0x3d, 0x57, 0x59, 0xd2, 0x1c, 0xce,
	0x11, 0x45, 0xa3, 0x39, 0x89, 0x05, 0x25, 0x9a, 0xed, 0xa3, 0x8c, 0x5d, 0xcc, 0x44, 0xc6, 0x28,
	0x0a, 0xd7, 0x8a, 0x3c, 0xf8, 0xd1, 0x01, 0x7d, 0x7b, 0xee, 0x2f, 0xe7, 0x13, 0xf8, 0x08, 0x74,
	0x4f, 0x84, 0xe4, 0x70, 0x1b, 0x57, 0x2b, 0xc3, 0xcb, 0x7d, 0xe2, 0xc3, 0x72, 0x9f, 0x5e, 0xcb,
	0x3d, 0x54, 0xa0, 0x5f, 0xbd, 0x77, 0xb5, 0xc5, 0x11, 0xfe, 0xe3, 0x8f, 0x85, 0x7f, 0xf5, 0xe5,
	0xdd, 0x69, 0x21, 0xec, 0x32, 0x68, 0xf0, 0xee, 0xf3, 0xf7, 0x0f, 0x6e, 0x1f, 0x5e, 0x1f, 0xdb,
	0x18, 0x64, 0xa0, 0xff, 0x94, 0xd2, 0x46, 0xe0, 0xdf, 0x94, 0x6b, 0x6b, 0x60, 0x19, 0x83, 0xd6,
	0x62, 0xa6, 0x00, 0x9e, 0xa6, 0xe5, 0x20, 0xff, 0x79, 0x92, 0xf7, 0x7b, 0xd2, 0x33, 0x16, 0xb3,
	0xff, 0x90, 0x74, 0xaf, 0x99, 0x74, 0xb0, 0x73, 0xf9, 0xd5, 0xdf, 0xb8, 0x5c, 0xf8, 0xce, 0xa7,
	0x85, 0xef, 0x7c, 0x59, 0xf8, 0xce, 0xc7, 0x6f, 0xfe, 0xc6, 0xab, 0x0e, 0x49, 0x45, 0x74, 0xd5,
	0x54, 0x78, 0xf8, 0x33, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x4b, 0xdd, 0x6c, 0x1f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrganizationSvcClient is the client API for OrganizationSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrganizationSvcClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetOrganization(ctx context.Context, in *GetOrgReq, opts ...grpc.CallOption) (*Organization, error)
	AddOrganization(ctx context.Context, in *Organization, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateOrganization(ctx context.Context, in *Organization, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteOrganization(ctx context.Context, in *Organization, opts ...grpc.CallOption) (*empty.Empty, error)
}

type organizationSvcClient struct {
	cc *grpc.ClientConn
}

func NewOrganizationSvcClient(cc *grpc.ClientConn) OrganizationSvcClient {
	return &organizationSvcClient{cc}
}

func (c *organizationSvcClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/eagle.organization.v1.OrganizationSvc/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationSvcClient) GetOrganization(ctx context.Context, in *GetOrgReq, opts ...grpc.CallOption) (*Organization, error) {
	out := new(Organization)
	err := c.cc.Invoke(ctx, "/eagle.organization.v1.OrganizationSvc/GetOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationSvcClient) AddOrganization(ctx context.Context, in *Organization, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/eagle.organization.v1.OrganizationSvc/AddOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationSvcClient) UpdateOrganization(ctx context.Context, in *Organization, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/eagle.organization.v1.OrganizationSvc/UpdateOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationSvcClient) DeleteOrganization(ctx context.Context, in *Organization, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/eagle.organization.v1.OrganizationSvc/DeleteOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizationSvcServer is the server API for OrganizationSvc service.
type OrganizationSvcServer interface {
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
	GetOrganization(context.Context, *GetOrgReq) (*Organization, error)
	AddOrganization(context.Context, *Organization) (*empty.Empty, error)
	UpdateOrganization(context.Context, *Organization) (*empty.Empty, error)
	DeleteOrganization(context.Context, *Organization) (*empty.Empty, error)
}

// UnimplementedOrganizationSvcServer can be embedded to have forward compatible implementations.
type UnimplementedOrganizationSvcServer struct {
}

func (*UnimplementedOrganizationSvcServer) Ping(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedOrganizationSvcServer) GetOrganization(ctx context.Context, req *GetOrgReq) (*Organization, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganization not implemented")
}
func (*UnimplementedOrganizationSvcServer) AddOrganization(ctx context.Context, req *Organization) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrganization not implemented")
}
func (*UnimplementedOrganizationSvcServer) UpdateOrganization(ctx context.Context, req *Organization) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrganization not implemented")
}
func (*UnimplementedOrganizationSvcServer) DeleteOrganization(ctx context.Context, req *Organization) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrganization not implemented")
}

func RegisterOrganizationSvcServer(s *grpc.Server, srv OrganizationSvcServer) {
	s.RegisterService(&_OrganizationSvc_serviceDesc, srv)
}

func _OrganizationSvc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationSvcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eagle.organization.v1.OrganizationSvc/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationSvcServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationSvc_GetOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationSvcServer).GetOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eagle.organization.v1.OrganizationSvc/GetOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationSvcServer).GetOrganization(ctx, req.(*GetOrgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationSvc_AddOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Organization)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationSvcServer).AddOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eagle.organization.v1.OrganizationSvc/AddOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationSvcServer).AddOrganization(ctx, req.(*Organization))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationSvc_UpdateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Organization)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationSvcServer).UpdateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eagle.organization.v1.OrganizationSvc/UpdateOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationSvcServer).UpdateOrganization(ctx, req.(*Organization))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationSvc_DeleteOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Organization)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationSvcServer).DeleteOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eagle.organization.v1.OrganizationSvc/DeleteOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationSvcServer).DeleteOrganization(ctx, req.(*Organization))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrganizationSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eagle.organization.v1.OrganizationSvc",
	HandlerType: (*OrganizationSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OrganizationSvc_Ping_Handler,
		},
		{
			MethodName: "GetOrganization",
			Handler:    _OrganizationSvc_GetOrganization_Handler,
		},
		{
			MethodName: "AddOrganization",
			Handler:    _OrganizationSvc_AddOrganization_Handler,
		},
		{
			MethodName: "UpdateOrganization",
			Handler:    _OrganizationSvc_UpdateOrganization_Handler,
		},
		{
			MethodName: "DeleteOrganization",
			Handler:    _OrganizationSvc_DeleteOrganization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func (m *Organization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Organization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Organization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ContactPhone) > 0 {
		i -= len(m.ContactPhone)
		copy(dAtA[i:], m.ContactPhone)
		i = encodeVarintApi(dAtA, i, uint64(len(m.ContactPhone)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ContactEmail) > 0 {
		i -= len(m.ContactEmail)
		copy(dAtA[i:], m.ContactEmail)
		i = encodeVarintApi(dAtA, i, uint64(len(m.ContactEmail)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ContactName) > 0 {
		i -= len(m.ContactName)
		copy(dAtA[i:], m.ContactName)
		i = encodeVarintApi(dAtA, i, uint64(len(m.ContactName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintApi(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintApi(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetOrgReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetOrgReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetOrgReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.OrganizationId) > 0 {
		i -= len(m.OrganizationId)
		copy(dAtA[i:], m.OrganizationId)
		i = encodeVarintApi(dAtA, i, uint64(len(m.OrganizationId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintApi(dAtA []byte, offset int, v uint64) int {
	offset -= sovApi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Organization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	l = len(m.ContactName)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	l = len(m.ContactEmail)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	l = len(m.ContactPhone)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetOrgReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrganizationId)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovApi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApi(x uint64) (n int) {
	return sovApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Organization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Organization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Organization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContactName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContactName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContactEmail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContactEmail = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContactPhone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContactPhone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetOrgReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetOrgReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetOrgReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrganizationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrganizationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApi = fmt.Errorf("proto: unexpected end of group")
)
