[Client]
	addr = "host.docker.internal:3306"
	dsn = "root:chwing@tcp(host.docker.internal:3306)/eagle_eye_local?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	readDSN = ["root:chwing@tcp(host.docker.internal:3306)/eagle_eye_local?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8","root:chwing@tcp(host.docker.internal:3306)/eagle_eye_local?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "200ms"
	execTimeout = "300ms"
	tranTimeout = "400ms"
